# Generated by Django 4.0.4 on 2022-04-29 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DishToAttributeMappingA',
            new_name='DishToAttributeMapping',
        ),
    ]
