# Generated by Django 4.0.4 on 2022-05-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_dish_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishtype',
            name='displayName',
            field=models.TextField(default='asd', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dishtype',
            name='image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dishtype',
            name='name',
            field=models.TextField(max_length=30),
        ),
    ]
